### ISSUE TITLE
new streams support, please

### ISSUE THREAD

**Issue by naugtur** [request/request#1402]
There's plenty of issues with streams since node 0.10 

This code will fail, but only under load. If the response is a file, it will be missing a few bytes from the beginning.

``` javascript
var requestObject = request(...)
// need to pause here requestObject.pause()
requestObject.on('response', function (resp) {
  if(resp.statusCode===200){
    requestObject.pipe(somewhere)
  }else{
    //retry...
  }
});
```

pausing `requestObject` saves the day, but it doesn't get resumed when you call `requestObject.pipe` and has to be resumed manually.

Now the other way:

if I pass an option:

``` javascript
formData:{
  file: stream
}
```

All's well, request is sent, but no content-type and filename set.
So I go on and do:

``` javascript
formData:{
  file: {
    value:stream,
    options:{
      filename: "whatever", //silently required, see https://github.com/felixge/node-form-data/issues/74
      contentType: "text/xml"
    }
  }
}
```

If `stream` is a plain string, all works well. If `stream` is a new node 0.10 stream, it hangs forever.

Seems serious to me.

This bug could be split in two if the first case can be fixed without intervention in `form-data`. In that case, let me know how I could help and where to start looking if I want to make a PR.

PS. I wrote the code in github textbox and tried to make indents with tab and space so it got submitted too early.

**Comment by nylen** [comment]
We agree, this is the plan for version `3.0` but it may take a while.  Generally we feel that the code needs some serious cleanup before major changes like that, we've made good progress on the test suite and we're currently working on splitting out features into separate files to help with maintainability.

Want to help?

**Comment by arcanis** [comment]
The first bug is pretty serious, I'm also missing a few bytes at the beginning of the files (despite the server sending the right amount of data, and the content-length header being correctly set).

**Comment by naugtur** [comment]
I responded via e-mail and now I see it broke...

I want to help. 

I think missing bytes (or a flowing stream) are a serious problem with the current version and it should be addressed in current major version if it's possible without changing the API.
The other issue is more of a problem in the dependency library, but maybe there's a way to wrap it if we sacrifice some runtime memory.

I could help separating features, but I don't think I know enough about `request` to be able to do that. At least not yet.

**Comment by odnarb** [comment]
Still an issue. Seems there was some effort before?

https://github.com/request/request/pull/660
