### ISSUE TITLE
The baseUrl gets ignored.

### ISSUE THREAD

**Issue by chrisngobanh** [request/request#1517]
```
var request = require('request')

var baseRequest = request.defaults({
  baseUrl: 'http://localhost:3000/api/'
})

baseRequest.get('/feed', function (err, response, body) {

      console.log(err)
    }
  )

```

The above code prints: `[Error: Invalid URI "/feed"]`

**Comment by bubenshchykov** [comment]
@chrisngobanh I have the same issue, how did u fix it?

**Comment by bubenshchykov** [comment]
ahh sorry it's fixed now )

**Comment by chrisngobanh** [comment]
@bubenshchykov My Request library was out of date. I was using a version that didn't have baseUrl implemented yet.

**Comment by larsnystrom** [comment]
Which version fixes this problem? I'm still experiencing it on 2.81.0.

**Comment by larsnystrom** [comment]
Sorry, I didn't realise the `defaults()` method returns a new `request` object instead of changing the settings globally. I should've RTFM, my bad.
